-- Insert new washing machines
INSERT INTO washing_machines (
  id,
  name,
  price,
  image,
  energy_class,
  capacity,
  rpm,
  features,
  rating,
  link,
  store,
  description,
  keywords,
  tier,
  created_at,
  updated_at
) VALUES
  (
    'power-wm2001',
    'AEG L8FEE965R',
    7499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1600,
    ARRAY['ProSteam®', 'ÖKOMix', 'ProSense®', 'Inverter Motor', 'SoftPlus'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/aeg-l8fee965r-vaskemaskine/p-1234567/',
    'Power',
    'Premium vaskemaskine med dampfunktion og ÖKOMix-teknologi for optimal vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'AEG', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2002',
    'Bosch WAV28MH9SN',
    8999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['i-DOS', 'Home Connect', '4D Wash System', 'AntiStain Plus', 'EcoSilence Drive'],
    4.6,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/bosch-wav28mh9sn-vaskemaskine/p-2345678/',
    'Power',
    'Intelligent vaskemaskine med automatisk dosering og app-styring',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2003',
    'Siemens WM14VEH9DN',
    9499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['i-DOS', 'speedPack', 'Home Connect', 'Outdoor/Impregnering', 'antiVibration Design'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/siemens-wm14veh9dn-vaskemaskine/p-3456789/',
    'Power',
    'Premium vaskemaskine med intelligent dosering og smart home-funktionalitet',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Siemens', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2004',
    'Electrolux EW8F7612BS',
    5999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    8,
    1600,
    ARRAY['SteamCare', 'SensiCare', 'TimeManager', 'Inverter Motor', 'Woolmark Blue'],
    4.5,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/electrolux-ew8f7612bs-vaskemaskine/p-4567890/',
    'Power',
    'Effektiv vaskemaskine med dampfunktion og skånsom vask',
    ARRAY['couple', 'weekly', 'Steamfunc', 'honeycomb-luxury', 'SelfDose', 'Electrolux', 'ecowash', 'Steam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2005',
    'Grundig GWN48430',
    4299,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'B',
    8,
    1400,
    ARRAY['Inverter EcoMotor', 'AquaWave', 'Hygiene+', 'Quick Wash', 'Pet Hair Removal'],
    4.2,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/grundig-gwn48430-vaskemaskine/p-5678901/',
    'Power',
    'Prisvenlig vaskemaskine med god energieffektivitet og specialprogrammer',
    ARRAY['couple', 'weekly', 'nosteam', 'normaldrum', 'SelfDose', 'Anybrand', 'Speedwash', 'nosteam'],
    'budget',
    now(),
    now()
  ),
  (
    'power-wm2006',
    'Whirlpool FWG81496WSE',
    4799,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'B',
    8,
    1400,
    ARRAY['6TH SENSE', 'FreshCare+', 'SoftMove', 'Colours15°', 'Steam Hygiene'],
    4.3,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/whirlpool-fwg81496wse-vaskemaskine/p-6789012/',
    'Power',
    'Intelligent vaskemaskine med 6TH SENSE-teknologi og dampfunktion',
    ARRAY['couple', 'weekly', 'Steamfunc', 'normaldrum', 'SelfDose', 'Anybrand', 'ecowash', 'Steam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2007',
    'LG F4V709S1E',
    7499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['AI DD™', 'TurboWash™ 360°', 'Steam+', 'Smart ThinQ™', 'Allergy Care'],
    4.8,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/lg-f4v709s1e-vaskemaskine/p-7890123/',
    'Power',
    'Intelligent vaskemaskine med AI-teknologi og hurtig vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2008',
    'Samsung WW90T986ASE',
    8999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1600,
    ARRAY['AI Control', 'QuickDrive™', 'EcoBubble™', 'AddWash™', 'Hygiene Steam'],
    4.8,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/samsung-ww90t986ase-vaskemaskine/p-8901234/',
    'Power',
    'Topmodel med AI-teknologi og QuickDrive for hurtigere og mere skånsom vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2009',
    'Bosch WAL28PH9SN',
    6999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['i-DOS', '4D Wash System', 'AntiStain', 'SpeedPerfect', 'EcoSilence Drive'],
    4.6,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/bosch-wal28ph9sn-vaskemaskine/p-9012345/',
    'Power',
    'Intelligent vaskemaskine med automatisk dosering og pletfjerningsprogrammer',
    ARRAY['family', 'weekly', 'nosteam', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'ecowash', 'nosteam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2010',
    'Siemens WM14VG90DN',
    8499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['i-DOS', 'speedPack', 'Home Connect', 'Outdoor/Impregnering', 'antiVibration Design'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/siemens-wm14vg90dn-vaskemaskine/p-0123456/',
    'Power',
    'Premium vaskemaskine med intelligent dosering og smart home-funktionalitet',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Siemens', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  );

-- Also update the products table with the same washing machines
INSERT INTO products (
  id,
  category_id,
  name,
  price,
  image,
  energy_class,
  capacity,
  features,
  rating,
  link,
  store,
  description,
  keywords,
  tier,
  created_at,
  updated_at
) VALUES
  (
    'power-wm2001',
    'washing_machines',
    'AEG L8FEE965R',
    7499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['ProSteam®', 'ÖKOMix', 'ProSense®', 'Inverter Motor', 'SoftPlus'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/aeg-l8fee965r-vaskemaskine/p-1234567/',
    'Power',
    'Premium vaskemaskine med dampfunktion og ÖKOMix-teknologi for optimal vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'AEG', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2002',
    'washing_machines',
    'Bosch WAV28MH9SN',
    8999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['i-DOS', 'Home Connect', '4D Wash System', 'AntiStain Plus', 'EcoSilence Drive'],
    4.6,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/bosch-wav28mh9sn-vaskemaskine/p-2345678/',
    'Power',
    'Intelligent vaskemaskine med automatisk dosering og app-styring',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2003',
    'washing_machines',
    'Siemens WM14VEH9DN',
    9499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['i-DOS', 'speedPack', 'Home Connect', 'Outdoor/Impregnering', 'antiVibration Design'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/siemens-wm14veh9dn-vaskemaskine/p-3456789/',
    'Power',
    'Premium vaskemaskine med intelligent dosering og smart home-funktionalitet',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Siemens', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2004',
    'washing_machines',
    'Electrolux EW8F7612BS',
    5999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    8,
    ARRAY['SteamCare', 'SensiCare', 'TimeManager', 'Inverter Motor', 'Woolmark Blue'],
    4.5,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/electrolux-ew8f7612bs-vaskemaskine/p-4567890/',
    'Power',
    'Effektiv vaskemaskine med dampfunktion og skånsom vask',
    ARRAY['couple', 'weekly', 'Steamfunc', 'honeycomb-luxury', 'SelfDose', 'Electrolux', 'ecowash', 'Steam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2005',
    'washing_machines',
    'Grundig GWN48430',
    4299,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'B',
    8,
    ARRAY['Inverter EcoMotor', 'AquaWave', 'Hygiene+', 'Quick Wash', 'Pet Hair Removal'],
    4.2,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/grundig-gwn48430-vaskemaskine/p-5678901/',
    'Power',
    'Prisvenlig vaskemaskine med god energieffektivitet og specialprogrammer',
    ARRAY['couple', 'weekly', 'nosteam', 'normaldrum', 'SelfDose', 'Anybrand', 'Speedwash', 'nosteam'],
    'budget',
    now(),
    now()
  ),
  (
    'power-wm2006',
    'washing_machines',
    'Whirlpool FWG81496WSE',
    4799,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'B',
    8,
    ARRAY['6TH SENSE', 'FreshCare+', 'SoftMove', 'Colours15°', 'Steam Hygiene'],
    4.3,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/whirlpool-fwg81496wse-vaskemaskine/p-6789012/',
    'Power',
    'Intelligent vaskemaskine med 6TH SENSE-teknologi og dampfunktion',
    ARRAY['couple', 'weekly', 'Steamfunc', 'normaldrum', 'SelfDose', 'Anybrand', 'ecowash', 'Steam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2007',
    'washing_machines',
    'LG F4V709S1E',
    7499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['AI DD™', 'TurboWash™ 360°', 'Steam+', 'Smart ThinQ™', 'Allergy Care'],
    4.8,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/lg-f4v709s1e-vaskemaskine/p-7890123/',
    'Power',
    'Intelligent vaskemaskine med AI-teknologi og hurtig vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2008',
    'washing_machines',
    'Samsung WW90T986ASE',
    8999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['AI Control', 'QuickDrive™', 'EcoBubble™', 'AddWash™', 'Hygiene Steam'],
    4.8,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/samsung-ww90t986ase-vaskemaskine/p-8901234/',
    'Power',
    'Topmodel med AI-teknologi og QuickDrive for hurtigere og mere skånsom vask',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  ),
  (
    'power-wm2009',
    'washing_machines',
    'Bosch WAL28PH9SN',
    6999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['i-DOS', '4D Wash System', 'AntiStain', 'SpeedPerfect', 'EcoSilence Drive'],
    4.6,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/bosch-wal28ph9sn-vaskemaskine/p-9012345/',
    'Power',
    'Intelligent vaskemaskine med automatisk dosering og pletfjerningsprogrammer',
    ARRAY['family', 'weekly', 'nosteam', 'honeycomb-luxury', 'Autodose', 'Anybrand', 'ecowash', 'nosteam'],
    'mid',
    now(),
    now()
  ),
  (
    'power-wm2010',
    'washing_machines',
    'Siemens WM14VG90DN',
    8499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['i-DOS', 'speedPack', 'Home Connect', 'Outdoor/Impregnering', 'antiVibration Design'],
    4.7,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/siemens-wm14vg90dn-vaskemaskine/p-0123456/',
    'Power',
    'Premium vaskemaskine med intelligent dosering og smart home-funktionalitet',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Siemens', 'PowerWash', 'Steam'],
    'premium',
    now(),
    now()
  );