-- Add 10 more products to all_products table

-- First ensure we have the latest schema
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_name = 'all_products' 
    AND column_name = 'type_specific_data'
  ) THEN
    ALTER TABLE all_products ADD COLUMN type_specific_data jsonb DEFAULT '{}'::jsonb;
  END IF;
END $$;

-- Insert new products
INSERT INTO all_products (
  id,
  name,
  price,
  image,
  energy_class,
  capacity,
  features,
  rating,
  link,
  store,
  description,
  keywords,
  tier,
  product_type,
  type_specific_data,
  created_at,
  updated_at
) VALUES
  (
    'power-wm3011',
    'Miele WWV980 WPS PWash & TDos',
    13999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    ARRAY['TwinDos', 'PowerWash', 'SteamCare', 'SingleWash', 'WiFiConn@ct', 'CapDosing'],
    5.0,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/miele-wwv980-wps-pwash-tdos-vaskemaskine/p-1234567/',
    'Power',
    'Topmodellen fra Miele med TwinDos automatisk dosering og dampfunktion',
    ARRAY['largefamily', 'everyday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'miele', 'PowerWash', 'Steam'],
    'premium',
    'washing_machine',
    '{"rpm": 1600, "annual_energy_consumption": 130, "annual_water_consumption": 9500}'::jsonb,
    now(),
    now()
  ),
  (
    'power-dw3011',
    'Miele G 7960 SCVi',
    15999,
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    14,
    ARRAY['AutoDos', '3D MultiFlex', 'AutoOpen', 'BrilliantLight', 'Extra Clean Zone'],
    5.0,
    'https://www.power.dk/hvidevarer/opvaskemaskine/integrerbare-opvaskemaskiner/miele-g-7960-scvi-integreret-opvaskemaskine/p-2345678/',
    'Power',
    'Premium opvaskemaskine med automatisk dosering og perfekt glaspleje',
    ARRAY['household-family', 'glass-PerfectGlassCare', 'usage-all', 'type-integrated', 'noise-bedroom-nearby', 'lifespan-high'],
    'premium',
    'dishwasher',
    '{"noise_level": 41, "place_settings": 14, "annual_energy_consumption": 64, "annual_water_consumption": 2492}'::jsonb,
    now(),
    now()
  ),
  (
    'power-ov3011',
    'Miele H 7890 BP',
    24999,
    'https://images.unsplash.com/photo-1585351923007-bf6a01cb19de?auto=format&fit=crop&q=80&w=400&h=400',
    'A+',
    76,
    ARRAY['TasteControl', 'FoodView', 'Moisture Plus', 'Wireless Food Probe', 'M Touch'],
    5.0,
    'https://www.power.dk/hvidevarer/ovn-og-komfur/indbygningsovn/miele-h-7890-bp-indbygningsovn/p-3456789/',
    'Power',
    'Topklasse indbygningsovn med kamera og dampfunktion',
    ARRAY['usage-Everyday', 'baking-FullSteam', 'maintenance-Pyrolyse', 'cooking_skill-ProChef', 'household_size-Family', 'heating_speed-quickheat', 'sousvide-Sousvide'],
    'premium',
    'oven',
    '{"max_temperature": 300, "has_pyrolysis": true, "has_steam": true, "number_of_functions": 45}'::jsonb,
    now(),
    now()
  ),
  (
    'power-rf3011',
    'Miele KFN 29683 D',
    19999,
    'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&q=80&w=400&h=400',
    'D',
    350,
    ARRAY['NoFrost', 'DynaCool', 'ComfortClean', 'DuplexCool', 'LED Lighting', 'FlexiLight'],
    5.0,
    'https://www.power.dk/hvidevarer/koeleskab/koele-fryseskab/miele-kfn-29683-d-koelefryseskab/p-4567890/',
    'Power',
    'Førsteklasses køle/fryseskab med optimal køling og lang holdbarhed',
    ARRAY['household-family', 'shopping-weeklyshopping', 'storage-meatdairy', 'energy-performance', 'freezer-bigfreezer', 'noise-quiet', 'dispenser-standarddoor', 'smart-nosmart', 'design-premiumdesign', 'size-standardfit'],
    'premium',
    'refrigerator',
    '{"freezer_capacity": 120, "refrigerator_capacity": 230, "no_frost": true, "climate_class": "SN-T", "noise_level": 36}'::jsonb,
    now(),
    now()
  ),
  (
    'power-wm3012',
    'Siemens iQ800 WM16XGH4DN',
    11999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    10,
    ARRAY['i-Dos', 'sensoFresh', 'Home Connect', 'speedPack', 'antiVibration Design'],
    4.9,
    'https://www.power.dk/hvidevarer/toejvask/frontbetjente-vaskemaskiner/siemens-iq800-wm16xgh4dn-vaskemaskine/p-5678901/',
    'Power',
    'Premium vaskemaskine med intelligent dosering og smart funktioner',
    ARRAY['family', 'almosteveryday', 'Steamfunc', 'honeycomb-luxury', 'Autodose', 'Siemens', 'PowerWash', 'Steam'],
    'premium',
    'washing_machine',
    '{"rpm": 1600, "annual_energy_consumption": 135, "annual_water_consumption": 9900}'::jsonb,
    now(),
    now()
  ),
  (
    'power-dw3012',
    'Bosch Serie 8 SMV8YCX01E',
    9999,
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400&h=400',
    'B',
    14,
    ARRAY['PerfectDry', 'Zeolith', 'Home Connect', 'EmotionLight', 'ExtraDry'],
    4.8,
    'https://www.power.dk/hvidevarer/opvaskemaskine/integrerbare-opvaskemaskiner/bosch-serie-8-smv8ycx01e-integreret-opvaskemaskine/p-6789012/',
    'Power',
    'Premium opvaskemaskine med Zeolith-tørring og smart funktioner',
    ARRAY['household-family', 'glass-PerfectGlassCare', 'usage-all', 'type-integrated', 'noise-bedroom-nearby', 'lifespan-high'],
    'premium',
    'dishwasher',
    '{"noise_level": 42, "place_settings": 14, "annual_energy_consumption": 65, "annual_water_consumption": 2660}'::jsonb,
    now(),
    now()
  ),
  (
    'power-ov3012',
    'Siemens iQ700 HN678G4S6',
    16999,
    'https://images.unsplash.com/photo-1585351923007-bf6a01cb19de?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    67,
    ARRAY['Home Connect', 'activeClean', 'pulseSteam', 'roastingSensor Plus', 'bakingSensor'],
    4.9,
    'https://www.power.dk/hvidevarer/ovn-og-komfur/indbygningsovn/siemens-iq700-hn678g4s6-indbygningsovn/p-7890123/',
    'Power',
    'Premium indbygningsovn med dampfunktion og smart styring',
    ARRAY['usage-Everyday', 'baking-FullSteam', 'maintenance-Pyrolyse', 'cooking_skill-ProChef', 'household_size-Family', 'heating_speed-quickheat', 'sousvide-Sousvide'],
    'premium',
    'oven',
    '{"max_temperature": 300, "has_pyrolysis": true, "has_steam": true, "number_of_functions": 40}'::jsonb,
    now(),
    now()
  ),
  (
    'power-rf3012',
    'LG GR-X29FTQKL',
    21999,
    'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&q=80&w=400&h=400',
    'D',
    635,
    ARRAY['InstaView', 'Door-in-Door', 'LinearCooling', 'CustomChill', 'UV nano'],
    4.9,
    'https://www.power.dk/hvidevarer/koeleskab/side-by-side-koeleskab/lg-gr-x29ftqkl-american-koeleskab/p-8901234/',
    'Power',
    'Luksuriøst side-by-side køleskab med InstaView og smart teknologi',
    ARRAY['household-largefamily', 'shopping-bulkshopping', 'storage-drinksnacks', 'energy-performance', 'freezer-bigfreezer', 'noise-quiet', 'dispenser-waterice', 'smart-smartcontrol', 'design-premiumdesign', 'size-largefit'],
    'premium',
    'refrigerator',
    '{"freezer_capacity": 235, "refrigerator_capacity": 400, "no_frost": true, "climate_class": "SN-T", "noise_level": 39}'::jsonb,
    now(),
    now()
  ),
  (
    'power-rf3013',
    'Samsung RF65A967FSR',
    24999,
    'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&q=80&w=400&h=400',
    'E',
    647,
    ARRAY['Family Hub', 'Beverage Center', 'Dual Ice Maker', 'Triple Cooling', 'FlexZone'],
    4.8,
    'https://www.power.dk/hvidevarer/koeleskab/side-by-side-koeleskab/samsung-rf65a967fsr-american-koeleskab/p-9012345/',
    'Power',
    'Premium side-by-side køleskab med Family Hub og avancerede funktioner',
    ARRAY['household-largefamily', 'shopping-bulkshopping', 'storage-drinksnacks', 'energy-performance', 'freezer-bigfreezer', 'noise-quiet', 'dispenser-waterice', 'smart-smartscreen', 'design-premiumdesign', 'size-largefit'],
    'premium',
    'refrigerator',
    '{"freezer_capacity": 247, "refrigerator_capacity": 400, "no_frost": true, "climate_class": "SN-T", "noise_level": 41}'::jsonb,
    now(),
    now()
  ),
  (
    'power-ov3013',
    'AEG BSK999330M',
    14999,
    'https://images.unsplash.com/photo-1585351923007-bf6a01cb19de?auto=format&fit=crop&q=80&w=400&h=400',
    'A+',
    70,
    ARRAY['SteamPro', 'SousVide', 'ConnectedCooking', 'SenseCook', 'PyrolyticPlus'],
    4.8,
    'https://www.power.dk/hvidevarer/ovn-og-komfur/indbygningsovn/aeg-bsk999330m-indbygningsovn/p-0123456/',
    'Power',
    'Professionel indbygningsovn med sous-vide og dampfunktioner',
    ARRAY['usage-Everyday', 'baking-FullSteam', 'maintenance-Pyrolyse', 'cooking_skill-ProChef', 'household_size-Family', 'heating_speed-quickheat', 'sousvide-Sousvide'],
    'premium',
    'oven',
    '{"max_temperature": 300, "has_pyrolysis": true, "has_steam": true, "number_of_functions": 35}'::jsonb,
    now(),
    now()
  );