/*
  # Add more washing machines

  1. New Data
    - Adding 10 new washing machines from Power.dk
    - Each machine includes:
      - Full specifications
      - Features
      - Keywords for matching
      - Tier categorization
*/

INSERT INTO washing_machines (
  id,
  name,
  price,
  image,
  energy_class,
  capacity,
  rpm,
  features,
  rating,
  link,
  store,
  description,
  keywords,
  tier
) VALUES
  (
    'lg-f4wv510s0e',
    'LG F4WV510S0E',
    5999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    10.5,
    1400,
    ARRAY['AI DD™ teknologi', 'Steam™', 'TurboWash™', 'Smart ThinQ™'],
    4.6,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/lg-f4wv510s0e-vaskemaskine/p-1207286/',
    'Power',
    'Rummelig vaskemaskine med smart teknologi og dampfunktion',
    ARRAY['household-large-family', 'efficiency-economic', 'duration-normal', 'frequency-daily'],
    'premium'
  ),
  (
    'samsung-ww95ta046ae',
    'Samsung WW95TA046AE',
    4999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['EcoBubble™', 'Digital Inverter Motor', 'Smart Control+', 'Hygiene Steam'],
    4.5,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/samsung-ww95ta046ae-vaskemaskine/p-1192456/',
    'Power',
    'Energieffektiv vaskemaskine med smart styring',
    ARRAY['household-family', 'efficiency-very-economic', 'duration-eco', 'frequency-frequent'],
    'mid'
  ),
  (
    'bosch-wau28pb9sn',
    'Bosch WAU28PB9SN',
    5499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['EcoSilence Drive', 'SpeedPerfect', 'ActiveWater Plus', '4D Wash System'],
    4.7,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/bosch-wau28pb9sn-vaskemaskine/p-1156789/',
    'Power',
    'Støjsvag og pålidelig vaskemaskine med høj kvalitet',
    ARRAY['household-family', 'efficiency-economic', 'duration-normal', 'frequency-frequent'],
    'mid'
  ),
  (
    'siemens-wm14ut69sn',
    'Siemens WM14UT69SN',
    6999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['iDos', 'speedPack', 'iQdrive', 'Outdoor/Impregnering'],
    4.8,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/siemens-wm14ut69sn-vaskemaskine/p-1189076/',
    'Power',
    'Premium vaskemaskine med automatisk dosering',
    ARRAY['household-family', 'efficiency-very-economic', 'duration-normal', 'frequency-daily'],
    'premium'
  ),
  (
    'aeg-l7fe86pro',
    'AEG L7FE86PRO',
    4499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    8,
    1600,
    ARRAY['ProSense®', 'ProSteam®', 'ÖKOMix', 'SoftPlus'],
    4.5,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/aeg-l7fe86pro-vaskemaskine/p-1187654/',
    'Power',
    'Professionel vaskemaskine med dampfunktion',
    ARRAY['household-couple', 'efficiency-economic', 'duration-eco', 'frequency-weekly'],
    'mid'
  ),
  (
    'whirlpool-ffb8248bvee',
    'Whirlpool FFB8248BVEE',
    3999,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    8,
    1200,
    ARRAY['FreshCare+', '6TH SENSE', 'SoftMove', 'Clean+'],
    4.3,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/whirlpool-ffb8248bvee-vaskemaskine/p-1156789/',
    'Power',
    'Prisvenlig vaskemaskine med gode basisfunktioner',
    ARRAY['household-couple', 'efficiency-standard', 'duration-normal', 'frequency-weekly'],
    'budget'
  ),
  (
    'electrolux-ew6f4r28w8',
    'Electrolux EW6F4R28W8',
    3799,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    8,
    1400,
    ARRAY['SensiCare', 'TimeManager', 'AutoSense', 'EcoTimer'],
    4.2,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/electrolux-ew6f4r28w8-vaskemaskine/p-1156789/',
    'Power',
    'Energibesparende vaskemaskine til den prisbevidste',
    ARRAY['household-couple', 'efficiency-economic', 'duration-quick', 'frequency-frequent'],
    'budget'
  ),
  (
    'lg-f4v709s1e',
    'LG F4V709S1E',
    7499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['AI DD™', 'TurboWash™ 360°', 'Steam+', 'Smart ThinQ™'],
    4.8,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/lg-f4v709s1e-vaskemaskine/p-1178965/',
    'Power',
    'Intelligent vaskemaskine med avanceret teknologi',
    ARRAY['household-family', 'efficiency-very-economic', 'duration-quick', 'frequency-daily'],
    'premium'
  ),
  (
    'samsung-ww90t534dae',
    'Samsung WW90T534DAE',
    4299,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['EcoBubble™', 'Digital Inverter Motor', 'Bubble Soak', 'Quick Wash'],
    4.4,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/samsung-ww90t534dae-vaskemaskine/p-1155653/',
    'Power',
    'Pålidelig vaskemaskine med god energieffektivitet',
    ARRAY['household-family', 'efficiency-economic', 'duration-quick', 'frequency-frequent'],
    'mid'
  ),
  (
    'bosch-wgg244a0sn',
    'Bosch WGG244A0SN',
    3499,
    'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=400',
    'A',
    9,
    1400,
    ARRAY['EcoSilence Drive', 'SpeedPerfect', 'ActiveWater™', 'AllergyPlus'],
    4.3,
    'https://www.power.dk/hvidevarer/vask-og-toer/vaskemaskiner/bosch-wgg244a0sn-vaskemaskine/p-1156789/',
    'Power',
    'Støjsvag og energieffektiv basismodel',
    ARRAY['household-family', 'efficiency-standard', 'duration-normal', 'frequency-weekly'],
    'budget'
  );